
Metrics/LineLength:
  Max: 90

Metrics/ClassLength:
  Max: 125

Metrics/AbcSize:
  Max: 19

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'capybara/*'
    - 'utils/test_utils.rb'