language: ruby
dist: trusty
sudo: required
addons:
  chrome: stable

before_install:
  - gem install bundler
  - bundle config build.nokogiri --use-system-libraries

script: rake features

rvm:
  - 2.4.0